name: sim_data_app
description: Sports KPI Simulator - robust saving to chosen folder
publish_to: "none"
version: 1.1.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  csv: ^6.0.0
  file_selector: ^1.0.3         # only for folder picker (optional, with fallback)
  path_provider: ^2.1.3         # to locate Downloads/Documents/Home

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
